package com.example.uit_project;

import android.graphics.drawable.Drawable;
import android.widget.RelativeLayout;

public class GlobalVar {
    public static String baseUrl = "https://uiot.ixxc.dev/";
    //    public static String signUpUrl = baseUrl + "auth/realms/master/login-actions/";
//    public static String tokenUrl = baseUrl + "auth/realms/master/protocol/openid-connect/token";
//    public static String resetUrl = baseUrl + "auth/realms/master/account/password";
    public static String LOG_TAG = "API LOG";

    public static LanguageManager manager;
    public static int drawableProfile = 0;
    public static RelativeLayout view;
    public static String token = "";
    public static String tokenProfile = "";
    //public static String token = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJoREkwZ2hyVlJvaE5zVy1wSXpZeDBpT2lHMzNlWjJxV21sRk4wWGE1dWkwIn0.eyJleHAiOjE3MDIzNjE3ODMsImlhdCI6MTcwMjI3NTM4MywiYXV0aF90aW1lIjoxNzAyMjc1MzgzLCJqdGkiOiI0YTIyOWI4ZS05NGI2LTQ1OGYtYTg1My0xZjlhYzc3NTVlNzQiLCJpc3MiOiJodHRwczovL3Vpb3QuaXh4Yy5kZXYvYXV0aC9yZWFsbXMvbWFzdGVyIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6IjRlM2E0NDk2LTJmMTktNDgxMy1iZjAwLTA5NDA3ZDFlZThjYiIsInR5cCI6IkJlYXJlciIsImF6cCI6Im9wZW5yZW1vdGUiLCJzZXNzaW9uX3N0YXRlIjoiNjFjOTAyOTEtNGExNS00OWQ0LTgwYTgtYzJkOTQzMGM1NDQxIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwczovL3Vpb3QuaXh4Yy5kZXYiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtbWFzdGVyIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7Im9wZW5yZW1vdGUiOnsicm9sZXMiOlsicmVhZDptYXAiLCJyZWFkOnJ1bGVzIiwicmVhZDppbnNpZ2h0cyIsInJlYWQ6YXNzZXRzIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJzaWQiOiI2MWM5MDI5MS00YTE1LTQ5ZDQtODBhOC1jMmQ5NDMwYzU0NDEiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJEbyBLaWVuIiwicHJlZmVycmVkX3VzZXJuYW1lIjoidXNlciIsImdpdmVuX25hbWUiOiJEbyIsImZhbWlseV9uYW1lIjoiS2llbiIsImVtYWlsIjoidXNlckBpeHhjLmRldiJ9.G8DgYcFedyDMYs-yJDhBYu7pFvLhMcetcFYgotq0WzwPylS3htywPMzsJmfTUZxjV4nP0fj909s95-EGkzRXS34pNEzK_G2SddiTkxI4ETYt2ndKdwyu6QEe-jbep2Ma_AkcWCOrXPDJLhqFQrgHJ0tQaqLmm5JFQnjBv3CIHW-MHssVs3V5BdIsO_u8QMqWLKtjFQcQfCpqeX2h7pzFLC7nwLtsXRM85cSeGB-HBcsp08K4wnN_w9NmuQiBpZxk3ej-DeJXfoCACG3MmoeagSAHqj-ByGAqA38Gs9gDpBQ6h6K64ZLDMNFbKfslLg9xVnCVzGeuB1ZoqkRQNi-b-w";
}