package com.example.uit_project;

import android.widget.RelativeLayout;

public class GlobalVar {
    public static String baseUrl = "https://uiot.ixxc.dev/";
//    public static String signUpUrl = baseUrl + "auth/realms/master/login-actions/";
//    public static String tokenUrl = baseUrl + "auth/realms/master/protocol/openid-connect/token";
//    public static String resetUrl = baseUrl + "auth/realms/master/account/password";
    public static String LOG_TAG = "API LOG";

    public static LanguageManager manager;
    public static RelativeLayout view;
    public static String token = " eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJoREkwZ2hyVlJvaE5zVy1wSXpZeDBpT2lHMzNlWjJxV21sRk4wWGE1dWkwIn0.eyJleHAiOjE3MDIwNTU1OTEsImlhdCI6MTcwMTk2OTIyNSwiYXV0aF90aW1lIjoxNzAxOTY5MTkxLCJqdGkiOiIyYzkyODkzNy1iODBkLTQ1NDQtYTRmZC0wMTQzNjA4MmQzYzciLCJpc3MiOiJodHRwczovL3Vpb3QuaXh4Yy5kZXYvYXV0aC9yZWFsbXMvbWFzdGVyIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6IjRlM2E0NDk2LTJmMTktNDgxMy1iZjAwLTA5NDA3ZDFlZThjYiIsInR5cCI6IkJlYXJlciIsImF6cCI6Im9wZW5yZW1vdGUiLCJzZXNzaW9uX3N0YXRlIjoiOGU3YzM1YjktMzNlOC00MjI1LTgzODgtZGRhMmY5MDUzZjIwIiwiYWNyIjoiMCIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwczovL3Vpb3QuaXh4Yy5kZXYiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtbWFzdGVyIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7Im9wZW5yZW1vdGUiOnsicm9sZXMiOlsicmVhZDptYXAiLCJyZWFkOnJ1bGVzIiwicmVhZDppbnNpZ2h0cyIsInJlYWQ6YXNzZXRzIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwic2lkIjoiOGU3YzM1YjktMzNlOC00MjI1LTgzODgtZGRhMmY5MDUzZjIwIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoiRmlyc3QgTmFtZSBMYXN0IG5hbWUiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIiwiZ2l2ZW5fbmFtZSI6IkZpcnN0IE5hbWUiLCJmYW1pbHlfbmFtZSI6Ikxhc3QgbmFtZSIsImVtYWlsIjoidXNlckBpeHhjLmRldiJ9.WSiCv-DTjehn3DCLKLRHsM-RTPl159cL2CQ18P1G0vZg_yaa4LzmxC-pVC8FiEqWIhEILM5Y8zZ4BCXZvEvZQzK3dZH5_FdcJQHMrjxCnM-hJBIfwm3aL7OYwrbPSePO0obdBHItRGI4TUlMarAZEfrbKeityd4A8SLDAG_1D2bZynz6aOB1VF7eoesFfhL0Ch7cBrqS0zGLrKexLoeV4PYETE2gXR-mo3M2-8WlGQDfi4igJxgbjIzsjiR_queX_mvAs456jw4aFmxjGagA2vMdywHmCMuaV1dzuikGb45QBxwnYPBBTDQ3jLQ-SuocJbpE3Pz-mrsAZg_JR5W_Jg";


}