package com.example.uit_project;

import android.widget.RelativeLayout;

public class GlobalVar {
    public static String baseUrl = "https://uiot.ixxc.dev/";
//    public static String signUpUrl = baseUrl + "auth/realms/master/login-actions/";
//    public static String tokenUrl = baseUrl + "auth/realms/master/protocol/openid-connect/token";
//    public static String resetUrl = baseUrl + "auth/realms/master/account/password";
    public static String LOG_TAG = "API LOG";

    public static LanguageManager manager;
    public static RelativeLayout view;
    public static String token = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJoREkwZ2hyVlJvaE5zVy1wSXpZeDBpT2lHMzNlWjJxV21sRk4wWGE1dWkwIn0.eyJleHAiOjE3MDIxODI3MjAsImlhdCI6MTcwMjA5OTIyNCwiYXV0aF90aW1lIjoxNzAyMDk2MzIwLCJqdGkiOiI4NDJmYTExNS1jYTBjLTQ3NzgtYjI1Ni1iM2ZmOWZhMjY2MDkiLCJpc3MiOiJodHRwczovL3Vpb3QuaXh4Yy5kZXYvYXV0aC9yZWFsbXMvbWFzdGVyIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6IjRlM2E0NDk2LTJmMTktNDgxMy1iZjAwLTA5NDA3ZDFlZThjYiIsInR5cCI6IkJlYXJlciIsImF6cCI6Im9wZW5yZW1vdGUiLCJzZXNzaW9uX3N0YXRlIjoiZDQ0YTY1NjgtNmFmNy00MTQ3LWE3YjgtZjkyODU4NWVkOTc0IiwiYWNyIjoiMCIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwczovL3Vpb3QuaXh4Yy5kZXYiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtbWFzdGVyIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7Im9wZW5yZW1vdGUiOnsicm9sZXMiOlsicmVhZDptYXAiLCJyZWFkOnJ1bGVzIiwicmVhZDppbnNpZ2h0cyIsInJlYWQ6YXNzZXRzIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwic2lkIjoiZDQ0YTY1NjgtNmFmNy00MTQ3LWE3YjgtZjkyODU4NWVkOTc0IiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoiRmlyc3QgTmFtZSBMYXN0IG5hbWUiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIiwiZ2l2ZW5fbmFtZSI6IkZpcnN0IE5hbWUiLCJmYW1pbHlfbmFtZSI6Ikxhc3QgbmFtZSIsImVtYWlsIjoidXNlckBpeHhjLmRldiJ9.JA3PetXn5KDsh6DESlRhANb8hG9qCLlTjwGUnr6Tb7QbY-YjSsq3i_P0q_x47RACvW_-6AxIqYyEi4cAXVZLpM9aLv5eo75VUVAAJTsg6puW1qZ-m40NOctHaAu4ApjNyLfxo2nwntuWPZcNEnDCHkuFGpLglyOqWbAA5L7zUA9qL16gGWQuoYR_5QcYqE5uQUYabiKXTWtotVRBuZ5z6_quTfCt8KzcEUDqGRTXpXkK6ZqXkDafESZwoXIZf3UKFGebq4Zsq_JdRKxhC-FXYyvlm5A_OeGg57VeBGroI-Da4Xpl_nwtEz1Oi50ZjThNViuzu3K7Gc4WhiEjcZ5sZA";
}